export const FETCH_MOVIES_LIST = "FETCH_MOVIES_LIST";
export const ADD_MOVIES_LIST = "ADD_MOVIES_LIST";
export const FETCH_MOVIES_DETAIL = "FETCH_MOVIES_DETAIL";
export const ADD_MOVIES_DETAIL = "ADD_MOVIES_DETAIL";
